### ISSUE TITLE
Legacy system shutdown

### ISSUE THREAD

**Issue by padovan** [kernelci/kernelci-project#337]
It's finally time to put that system to sleep; I am sure it is quite tired already after all those kernel builds and test runs.

List of actions to be completed to shutdown our legacy system:

- [x]  [Warning added to email build, boot and test reports](https://github.com/kernelci/kernelci-backend/issues/303) by Apr 30
- [x]  [Warning added to the legacy web dashboard](https://github.com/kernelci/kernelci-frontend/issues/152) by Apr 30
- [x]  Early notice sent to kernelci mailing list  with no hard deadline set yet. Do it by May 30, 2024
- [x]  Disable outdated trees by May 30, 2024
- [x]  Enable baseline tests for all devices in the new system by June 30, 2024
- [x]  Decouple rootfs generation by July 31, 2024
- [x]  Decouple hugo website by July 31, 2024
- [x]  Reduce resource consumption as the new system scale up
- [ ]  [Enable all active devices/labs on the new system](https://github.com/kernelci/kernelci-project/issues/351) by July 31, 2024
- [ ]  Collect import usecases that users still have with the legacy system
- [x] https://github.com/kernelci/kernelci-project/issues/403
- [ ]  Move relevant test plans to the new system
- [ ]  Define shutdown timeline
- [ ]  Send definitive notice with deadline set
- [ ]  Send reminder 1 week before
- [ ]  Shutdown the system backend, but leave the web-dashboard alive for one or more months (Date TBD)
- [ ]  Shutdown everything!  (Date TBD) 
- [ ]  Keep database archive available for the general public

**Comment by gctucker** [comment]
Out of interest, is the database going to be archived somewhere?

**Comment by padovan** [comment]
> Out of interest, is the database going to be archived somewhere?

I just added a new item about that in the todo list.
