### ISSUE TITLE
Move missing content over from foundation website

### ISSUE THREAD

**Issue by patersonc** [kernelci/kernelci-project#43]
Currently only the "foundation" site details that the project is funded and can be joined.

We should add information about project membership to the static site as well in the [organization section](https://kernelci.org/docs/org/).

- [x] #47 with Membership/Members page
- [x] #48 ([info](https://github.com/kernelci/kernelci-project/issues/43#issuecomment-914066271))
- [x] #47 Add mission and objectives information ([info](https://github.com/kernelci/kernelci-project/issues/43#issuecomment-914066271))
- [x] #50 #52 Move news over to static website
- [x] #50 #52 
- [ ] Update links to foundation.kernelci.org to point to new static website
- [ ] Decommission/archive old website

**Comment by patersonc** [comment]
Hi @gctucker

If you're happy with this suggestion let me know and I'll pick it up this week.

Thanks, Chris

**Comment by gctucker** [comment]
Yes, this sounds good.  In fact, I think the plan is to move all the contents from foundation.kernelci.org to the static website.  There was some discussion on Slack a few weeks ago about that, please take a look.

**Comment by patersonc** [comment]
>Yes, this sounds good. In fact, I think the plan is to move all the contents from foundation.kernelci.org to the static website. There was some discussion on Slack a few weeks ago about that, please take a look.

Yes I saw that. I guess this can be a first (minor) step.

**Comment by gctucker** [comment]
Things that are on the foundation.kernelci.org website and not on the static kernelci.org one yet:
* https://foundation.kernelci.org/

> KernelCI is a community-based open source distributed test automation system focused on upstream kernel development. The primary goal of KernelCI is [...]

> The Linux kernel is developed by a large, collaborative open source community working together to continuously improve the software. [...]

> It was originally started in 2014 as a side project by a few engineers who were doing the testing at home and in their spare time. [...]

I believe these paragraphs should be moved to the "About" page with new sections with different background colours:
https://kernelci.org/about/

* Mission Statement on https://foundation.kernelci.org/mission-objectives/

This probably should be moved to the organization section in the docs:
https://kernelci.org/docs/org/

Then we could have a "Mission Statement" link on the home page or About page.

**Comment by gctucker** [comment]
Once this has been added to the kernelci.org website, the foundation.kernelci.org website would only have the Blog and News left.  Those can be moved to the Hugo kernelci.org website too as the theme we're using provides a Blog section.  Here's an example:
https://example.docsy.dev/blog/

**Comment by patersonc** [comment]
I wonder whether we should rename the `organization` page to `foundation`?

**Comment by patersonc** [comment]
Do we need to add this copyright text to the static site's footer?

> Copyright © 2021 Kernel CI The Linux Foundation® . All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page. Linux is a registered trademark of Linus Torvalds. Privacy Policy and Terms of Use.

(see bottom of the foundation site)

**Comment by gctucker** [comment]
No, the whole static website is not copyright of the Linux Foundation.  It's mixed copyright, documentation is being written by many different people and logos come from various companies etc.  Some documents such as the project charters are most likely under the LF copyright.

It's true we may need to improve things around that though, with something like "some rights reserved" in the footer and ideally copyright statements somewhere to cover all kinds of content.

**Comment by patersonc** [comment]
Unassigning from me as I don't think I have the power for the last two points.

**Comment by padovan** [comment]
This is outdated and we accomplished what we needed here.
